# Reddit
REDDIT_API_CREDENTIALS = {
    'client_id': '<YOUR_CLIENT_ID>',
    'client_secret': '<YOUR_CLIENT_SECRET>',
    'user_agent': '<YOUR_USER_AGENT>',
    'username': '<YOUR_USERNAME>',
    'password': '<YOUR_PASSWORD>',
}
THREAD = '<THREAD_TO_MONITOR>'

# sqlite3
DATABASE = '<PATH_TO_SQLITE3_DATABASE>'

# Slack
WEBHOOK_URL = '<SLACK_WEBHOOK_URL>'

# Twilio
NUMBERS = ['<TEXT_RECEPIENT_LIST>',] 
account_sid = '<YOUR_ACCOUNT_SID>'
auth_token = '<YOUR_AUTH_TOKEN>'
TWILIO_NUMBER = '<YOUR_TWILIO_NUMBER>'

# Other
KEYWORD_PRIMARY = '<KEYWORD_TO_MONITOR>'
KEYWORD_SECONDARY = '<KEYWORD_WHOSE_COMMENTS_MIGHT_CONTAIN_PRIMARY_KEYWORD>'

# test.py
PERSONAL_MOBILE_NUM = '<YOUR_MOBILE_NUMBER>'
TEST_WEBHOOK_URL = '<TEST_SLACK_WEBHOOK_URL>'